#!/bin/bash 
#SBATCH --job-name="AAA-0.1M"
#SBATCH -A uoo104
#SBATCH --output="OUT-AAA-MD.%j.%N.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH --export=ALL
#SBATCH -t 48:00:00


BD=$PWD
cd $BD
module load cpu/0.15.4 gcc/10.2.0 openmpi/4.0.4 gromacs/2020.4
module list
exe=`which gmx_mpi`


$exe grompp -f pro.mdp -p 2AP.top -c NVT_eq.pdb -o NPT_prod.tpr -maxwarn 5
if [ -f state_last.cpt ]; then
  mpirun $exe mdrun -v -s NPT_prod.tpr -deffnm NPT_prod -c NPT_last.pdb -cpo state_last.cpt 
else
  mpirun $exe mdrun -v -s NPT_prod.tpr -deffnm NPT_prod -c NPT_last.pdb -cpi state_last.cpt -cpo state_last.cpt
fi

exit
